### ISSUE TITLE
vite-plugin-iso-import is broken from SvelteKit 146 onward

### ISSUE THREAD

**Issue by kevinrenskers** [bluwy/vite-plugin-iso-import#1] opened 2021-09-05 17:38 UTC
See https://github.com/sveltejs/kit/issues/2371.

### Describe the bug

I was using [vite-plugin-iso-import](https://github.com/bluwy/vite-plugin-iso-import) successfully just fine for a few weeks. Today I updated SvelteKit from .144 to .162 and now I am getting this error when trying to start the server:

```
> The following dependencies are imported but could not be resolved:

  text-field-edit?client (imported by /Users/kevin/Workspace/cn-sveltekit/src/lib/components/Textarea.svelte)
  fit-textarea?client (imported by /Users/kevin/Workspace/cn-sveltekit/src/lib/components/Textarea.svelte)

Are they installed?
```

### Reproduction

My (simplified) `Textarea.svelte` component:

```
<script>
  import { onMount } from "svelte";
  import { insert, wrapSelection, getSelection } from "text-field-edit?client";
  import fitTextarea from "fit-textarea?client";

  export let value = "";
  let textarea;

  onMount(() => {
    fitTextarea.watch(textarea);
  });
</script>

<textarea rows="3" bind:value bind:this={textarea} />
```

My `svelte.config.js` file:

```
import md from "vite-plugin-markdown";
import { isoImport } from "vite-plugin-iso-import";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    vite: {
      plugins: [md.plugin({ mode: md.Mode.HTML }), isoImport()],
    },
  },
};

export default config;
```

After some trial and error it turns out it broke in SvelteKit .146 - it still works with .145.

**Comment by bluwy** [comment] 2021-09-05 18:28
The issue is that during Vite's prebundling, it's not able to resolve `package?client` as `package`. Currently I'm trying to add a custom esbuild plugin to intercept it but I'm having issues as `build.onResolve` requiring us to do the entire resolving ourselves instead of the "modify path and fallthrough" technique I'm familiar in rollup. Gonna have to investigate this again tomorrow.

**Comment by bluwy** [comment] 2021-09-06 07:42
This should be fixed in 0.1.2. Hope the fix works on your end too!

**Comment by kevinrenskers** [comment] 2021-09-06 10:09
Great, thanks! I'll test tonight.

**Comment by kevinrenskers** [comment] 2021-09-06 16:47
It works, thanks for the quick update!

**Closed as completed** 2021-09-06 17:49 UTC
